abort helper

diff --git a/bin/brew-publish b/bin/brew-publish
--- a/bin/brew-publish
+++ b/bin/brew-publish
@@ -5,12 +5,16 @@
 # request with the change.
 set -e
 
+abort() {
+  echo "$1" >&2
+  exit 1
+}
+
 brew_name="${1?}"
 version="${2?}"
 
 if ! type -p hub >/dev/null; then
-  "ERROR: You have to install hub to proceed." >&2
-  exit 1
+  abort "ERROR: You have to install hub to proceed."
 fi
 
 if [ -n "$3" ]; then
@@ -25,8 +29,7 @@ url="https://${gh_project/://}/archive/${version}.tar.gz"
 checksum="$(curl -fsSL "$url" | shasum -a 256 -b | awk '{print $1}')"
 
 if [ -z "$checksum" ]; then
-  echo "ERROR: calculating the checksum failed for $url" >&2
-  exit 1
+  abort "ERROR: calculating the checksum failed for $url"
 fi
 
 pushd "$(brew --prefix)"
